# arquivo para ci/cd AULA TI323 2026
name: CI/CD TI323

on: # [push] # como sera o gatilho
 push:
  branches:
    - main
  paths:
    - 'projeto/**'

 workflow_dispatch:
  inputs:
    environment:
      description: Força Bruta
      type: choice
      required: true
      default: dev
      options:
        - web
        - mac 

jobs: # trabalho a ser realizado
  informacao_sistema:
    runs-on: ubuntu-latest
    steps: # passo a serem executados 
      - name: Lista o diretorio corrente
        run: ls -la

  compila_o_projeto:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projeto
    steps:
      - name: Checkout code   
        uses: actions/checkout@v6
      - name: Lista para ver se os arquivos estao ai
        run: ls -Rla




